In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import streamlit as st

In [2]:
df = pd.read_csv('SolarPrediction.csv')
df

,UNIXTime,Data,Time,Radiation,Temperature,Pressure,Humidity,WindDirection(Degrees),Speed,TimeSunRise,TimeSunSet
0,1475229326,9/29/2016 12:00:00 AM,23:55:26,1.21,48,30.46,59,177.39,5.62,06:13:00,18:13:00
1,1475229023,9/29/2016 12:00:00 AM,23:50:23,1.21,48,30.46,58,176.78,3.37,06:13:00,18:13:00
2,1475228726,9/29/2016 12:00:00 AM,23:45:26,1.23,48,30.46,57,158.75,3.37,06:13:00,18:13:00
3,1475228421,9/29/2016 12:00:00 AM,23:40:21,1.21,48,30.46,60,137.71,3.37,06:13:00,18:13:00
4,1475228124,9/29/2016 12:00:00 AM,23:35:24,1.17,48,30.46,62,104.95,5.62,06:13:00,18:13:00
...,...,...,...,...,...,...,...,...,...,...,...
32681,1480587604,12/1/2016 12:00:00 AM,00:20:04,1.22,44,30.43,102,145.42,6.75,06:41:00,17:42:00
32682,1480587301,12/1/2016 12:00:00 AM,00:15:01,1.17,44,30.42,102,117.78,6.75,06:41:00,17:42:00
32683,1480587001,12/1/2016 12:00:00 AM,00:10:01,1.20,44,30.42,102,145.19,9.00,06:41:00,17:42:00
32684,1480586702,12/1/2016 12:00:00 AM,00:05:02,1.23,44,30.42,101,164.19,7.87,06:41:00,17:42:00
32685,1480586402,12/1/2016 12:00:00 AM,00:00:02,1.20,44,30.43,101,83.59,3.37,06:41:00,17:42:00

### 📊 Columns Description
| Column                      | Description                                                              | Unit                   |
| --------------------------- | ------------------------------------------------------------------------ | ---------------------- |
| **UNIXTime**                | Unix timestamp representing the number of seconds since January 1, 1970. | Seconds                |
| **Data**                    | Date of the observation in `MM/DD/YYYY` format.                          | -                      |
| **Time**                    | Local time of the observation in `HH:MM:SS` (24-hour format).            | -                      |
| **Radiation**               | Solar radiation measured at the weather station. *(Target variable)*     | W/m²                   |
| **Temperature**             | Ambient air temperature.                                                 | °F                     |
| **Pressure**                | Atmospheric pressure.                                                    | Inches of Mercury (Hg) |
| **Humidity**                | Relative humidity.                                                       | %                      |
| **WindDirection (Degrees)** | Wind direction measured clockwise from north.                            | Degrees (0–360°)       |
| **Speed**                   | Wind speed.                                                              | Miles per hour (mph)   |
| **TimeSunRise**             | Local sunrise time in Hawaii.                                            | HH:MM:SS               |
| **TimeSunSet**              | Local sunset time in Hawaii.                                             | HH:MM:SS               |

# Data Exploration

In [3]:
# Check data types 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32686 entries, 0 to 32685
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   UNIXTime                32686 non-null  int64
 1   Data                    32686 non-null  object
 2   Time                    32686 non-null  object
 3   Radiation               32686 non-null  float64
 4   Temperature             32686 non-null  int64
 5   Pressure                32686 non-null  float64
 6   Humidity                32686 non-null  int64
 7   WindDirection(Degrees)  32686 non-null  float64
 8   Speed                   32686 non-null  float64
 9   TimeSunRise             32686 non-null  object
 10  TimeSunSet              32686 non-null  object
dtypes: float64(4), int64(3), object(4)
memory usage: 2.7+ MB

* Check summary statistics for `Numerical` columns

In [4]:
df.describe(include='number').round(2)

,UNIXTime,Radiation,Temperature,Pressure,Humidity,WindDirection(Degrees),Speed
count,3.268600e+04,32686.00,32686.0,32686.00,32686.00,32686.00,32686.00
mean,1.478047e+09,207.12,51.1,30.42,75.02,143.49,6.24
std,3.005037e+06,315.92,6.2,0.05,25.99,83.17,3.49
min,1.472724e+09,1.11,34.0,30.19,8.00,0.09,0.00
25%,1.475546e+09,1.23,46.0,30.40,56.00,82.23,3.37
50%,1.478026e+09,2.66,50.0,30.43,85.00,147.70,5.62
75%,1.480480e+09,354.24,55.0,30.46,97.00,179.31,7.87
max,1.483265e+09,1601.26,71.0,30.56,103.00,359.95,40.50

* Check summary statistics for `Categorical` columns

In [5]:
df.describe(include='object')

                          Data      Time TimeSunRise TimeSunSet
count                    32686     32686       32686      32686
unique                     118      8299          51         56
top     10/19/2016 12:00:00 AM  16:20:18    06:11:00   17:42:00
freq                       288        24        1399       3682

- Check Duplicates

In [6]:
df.duplicated().sum()

np.int64(0)

- Check Missing Values

In [7]:
df.isna().sum()

UNIXTime                  0
Data                      0
Time                      0
Radiation                 0
Temperature               0
Pressure                  0
Humidity                  0
WindDirection(Degrees)    0
Speed                     0
TimeSunRise               0
TimeSunSet                0
dtype: int64

# Data Cleaning

In [8]:
# make all column names lowercase 
df.columns = df.columns.str.lower().str.strip()
df.columns

Index(['unixtime', 'data', 'time', 'radiation', 'temperature', 'pressure',
       'humidity', 'winddirection(degrees)', 'speed', 'timesunrise',
       'timesunset'],
      dtype='object')

In [9]:
# in depth check for categorical columns
cat_cols=df.select_dtypes(include='object').columns
cat_cols

Index(['data', 'time', 'timesunrise', 'timesunset'], dtype='object')

In [10]:
for col in cat_cols:
    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print(df[col].value_counts())
    print('#' * 50)

data
118
['9/29/2016 12:00:00 AM' '9/28/2016 12:00:00 AM' '9/27/2016 12:00:00 AM'
 '9/26/2016 12:00:00 AM' '9/25/2016 12:00:00 AM' '9/24/2016 12:00:00 AM'
 '9/23/2016 12:00:00 AM' '9/22/2016 12:00:00 AM' '9/21/2016 12:00:00 AM'
 '9/20/2016 12:00:00 AM' '9/19/2016 12:00:00 AM' '9/18/2016 12:00:00 AM'
 '9/17/2016 12:00:00 AM' '9/16/2016 12:00:00 AM' '9/15/2016 12:00:00 AM'
 '9/14/2016 12:00:00 AM' '9/13/2016 12:00:00 AM' '9/12/2016 12:00:00 AM'
 '9/11/2016 12:00:00 AM' '9/10/2016 12:00:00 AM' '9/9/2016 12:00:00 AM'
 '9/8/2016 12:00:00 AM' '9/7/2016 12:00:00 AM' '9/6/2016 12:00:00 AM'
 '9/5/2016 12:00:00 AM' '9/4/2016 12:00:00 AM' '9/3/2016 12:00:00 AM'
 '9/2/2016 12:00:00 AM' '9/1/2016 12:00:00 AM' '10/31/2016 12:00:00 AM'
 '10/30/2016 12:00:00 AM' '10/29/2016 12:00:00 AM'
 '10/28/2016 12:00:00 AM' '10/27/2016 12:00:00 AM'
 '10/26/2016 12:00:00 AM' '10/25/2016 12:00:00 AM'
 '10/24/2016 12:00:00 AM' '10/23/2016 12:00:00 AM'
 '10/22/2016 12:00:00 AM' '10/21/2016 12:00:00 AM'
 '10/20/2016 12:00:00 AM' '10/19/2016 12:00:00 AM'
 '10/18/2016 12:00:00 AM' '10/17/2016 12:00:00 AM'
 '10/16/2016 12:00:00 AM' '10/15/2016 12:00:00 AM'
 '10/14/2016 12:00:00 AM' '10/13/2016 12:00:00 AM'
 '10/12/2016 12:00:00 AM' '10/11/2016 12:00:00 AM'
 '10/10/2016 12:00:00 AM' '10/9/2016 12:00:00 AM' '10/8/2016 12:00:00 AM'
 '10/7/2016 12:00:00 AM' '10/6/2016 12:00:00 AM' '10/5/2016 12:00:00 AM'
 '10/4/2016 12:00:00 AM' '10/3/2016 12:00:00 AM' '10/2/2016 12:00:00 AM'
 '10/1/2016 12:00:00 AM' '11/29/2016 12:00:00 AM' '11/28/2016 12:00:00 AM'
 '11/27/2016 12:00:00 AM' '11/26/2016 12:00:00 AM'
 '11/25/2016 12:00:00 AM' '11/24/2016 12:00:00 AM'
 '11/23/2016 12:00:00 AM' '11/22/2016 12:00:00 AM'
 '11/21/2016 12:00:00 AM' '11/20/2016 12:00:00 AM'
 '11/19/2016 12:00:00 AM' '11/18/2016 12:00:00 AM'
 '11/17/2016 12:00:00 AM' '11/16/2016 12:00:00 AM'
 '11/15/2016 12:00:00 AM' '11/14/2016 12:00:00 AM'
 '11/13/2016 12:00:00 AM' '11/12/2016 12:00:00 AM'
 '11/11/2016 12:00:00 AM' '11/10/2016 12:00:00 AM' '11/9/2016 12:00:00 AM'
 '11/8/2016 12:00:00 AM' '11/7/2016 12:00:00 AM' '11/6/2016 12:00:00 AM'
 '11/5/2016 12:00:00 AM' '11/4/2016 12:00:00 AM' '11/3/2016 12:00:00 AM'
 '11/2/2016 12:00:00 AM' '11/1/2016 12:00:00 AM' '12/31/2016 12:00:00 AM'
 '12/30/2016 12:00:00 AM' '12/29/2016 12:00:00 AM'
 '12/28/2016 12:00:00 AM' '12/27/2016 12:00:00 AM'
 '12/26/2016 12:00:00 AM' '12/25/2016 12:00:00 AM'
 '12/24/2016 12:00:00 AM' '12/23/2016 12:00:00 AM'
 '12/22/2016 12:00:00 AM' '12/21/2016 12:00:00 AM'
 '12/20/2016 12:00:00 AM' '12/19/2016 12:00:00 AM'
 '12/18/2016 12:00:00 AM' '12/17/2016 12:00:00 AM'
 '12/16/2016 12:00:00 AM' '12/15/2016 12:00:00 AM'
 '12/14/2016 12:00:00 AM' '12/13/2016 12:00:00 AM'
 '12/12/2016 12:00:00 AM' '12/11/2016 12:00:00 AM'
 '12/10/2016 12:00:00 AM' '12/9/2016 12:00:00 AM' '12/8/2016 12:00:00 AM'
 '12/5/2016 12:00:00 AM' '12/4/2016 12:00:00 AM' '12/3/2016 12:00:00 AM'
 '12/2/2016 12:00:00 AM' '12/1/2016 12:00:00 AM']
data
10/19/2016 12:00:00 AM    288
10/18/2016 12:00:00 AM    288
10/21/2016 12:00:00 AM    288
10/20/2016 12:00:00 AM    288
10/29/2016 12:00:00 AM    288
                         ...
9/16/2016 12:00:00 AM     185
12/8/2016 12:00:00 AM     154
9/8/2016 12:00:00 AM      142
9/15/2016 12:00:00 AM     140
9/9/2016 12:00:00 AM      123
Name: count, Length: 118, dtype: int64
##################################################
time
8299
['23:55:26' '23:50:23' '23:45:26' ... '09:50:08' '09:35:13' '01:50:03']
time
16:20:18    24
20:05:18    21
15:45:18    21
18:45:18    21
19:20:18    21
            ..
20:00:08     1
20:45:07     1
20:50:38     1
21:15:33     1
21:25:41     1
Name: count, Length: 8299, dtype: int64
##################################################
timesunrise
51
['06:13:00' '06:12:00' '06:11:00' '06:10:00' '06:09:00' '06:08:00'
 '06:07:00' '06:23:00' '06:22:00' '06:21:00' '06:20:00' '06:19:00'
 '06:18:00' '06:17:00' '06:16:00' '06:15:00' '06:14:00' '06:40:00'
 '06:39:00' '06:38:00' '06:37:00' '06:36:00' '06:35:00' '06:34:00'
 '06:33:00' '06:32:00' '06:31:00' '06:30:00' '06:29:00' '06:28:00'
 '06:27:00' '06:26:00' '06:25:00' '06:24:00' '06:57:00' '06:56:00'
 '06:55:00' '06:54:00' '06:53:00' '06:52:00' '06:51:00' '06:50:00'
 '06:49:00' '06:48:00' '06:47:00' '06:46:00' '06:45:00' '06:44:00'
 '06:43:00' '06:42:00' '06:41:00']
timesunrise
06:11:00    1399
06:08:00    1327
06:10:00    1169
06:13:00    1132
06:14:00    1127
06:16:00    1127
06:12:00    1119
06:09:00    1026
06:19:00     864
06:56:00     863
06:23:00     862
06:21:00     860
06:18:00     853
06:15:00     851
06:17:00     844
06:35:00     576
06:31:00     576
06:38:00     576
06:28:00     576
06:48:00     576
06:54:00     576
06:42:00     576
06:30:00     576
06:55:00     576
06:27:00     576
06:22:00     575
06:47:00     575
06:26:00     575
06:53:00     575
06:32:00     575
06:34:00     575
06:51:00     574
06:37:00     574
06:24:00     574
06:20:00     574
06:25:00     574
06:52:00     574
06:57:00     573
06:50:00     573
06:07:00     529
06:39:00     288
06:43:00     288
06:33:00     288
06:41:00     288
06:29:00     288
06:46:00     288
06:36:00     287
06:49:00     286
06:44:00     249
06:40:00     230
06:45:00     154
Name: count, dtype: int64
##################################################
timesunset
56
['18:13:00' '18:14:00' '18:15:00' '18:16:00' '18:17:00' '18:18:00'
 '18:19:00' '18:20:00' '18:21:00' '18:22:00' '18:23:00' '18:24:00'
 '18:25:00' '18:26:00' '18:27:00' '18:28:00' '18:29:00' '18:30:00'
 '18:31:00' '18:32:00' '18:33:00' '18:34:00' '18:35:00' '18:36:00'
 '18:37:00' '18:38:00' '17:49:00' '17:50:00' '17:51:00' '17:52:00'
 '17:53:00' '17:54:00' '17:55:00' '17:56:00' '17:57:00' '17:58:00'
 '17:59:00' '18:00:00' '18:01:00' '18:02:00' '18:03:00' '18:04:00'
 '18:05:00' '18:06:00' '18:07:00' '18:08:00' '18:09:00' '18:10:00'
 '18:11:00' '17:42:00' '17:43:00' '17:44:00' '17:45:00' '17:46:00'
 '17:47:00' '17:48:00']
timesunset
17:42:00    3682
17:43:00    2264
17:44:00    1881
17:46:00    1722
17:45:00    1440
17:51:00    1151
17:52:00    1150
17:49:00    1149
17:48:00    1148
17:47:00    1148
17:54:00    1147
17:50:00     864
17:56:00     576
17:53:00     573
18:03:00     564
18:08:00     563
18:35:00     561
17:59:00     561
18:15:00     544
18:26:00     422
17:57:00     288
17:55:00     288
18:18:00     287
18:17:00     285
18:13:00     285
18:19:00     284
18:16:00     284
18:07:00     284
18:06:00     284
18:02:00     284
18:11:00     284
18:29:00     284
18:05:00     283
18:10:00     283
18:01:00     283
17:58:00     283
18:21:00     283
18:34:00     283
18:14:00     282
18:20:00     282
18:36:00     282
18:28:00     282
18:00:00     282
18:24:00     281
18:09:00     281
18:27:00     281
18:04:00     279
18:37:00     279
18:22:00     275
18:23:00     275
18:38:00     250
18:33:00     201
18:30:00     195
18:25:00     185
18:32:00     142
18:31:00     123
Name: count, dtype: int64
##################################################

In [11]:
# in depth check for numerical columns
num_cols=df.select_dtypes(include='number').columns
num_cols

Index(['unixtime', 'radiation', 'temperature', 'pressure', 'humidity',
       'winddirection(degrees)', 'speed'],
      dtype='object')

In [12]:
px.defaults.template = 'plotly_white'

In [13]:
## visualize the distribution of numerical columns using histogram and box plot
for col in num_cols:
    px.histogram(data_frame=df, x=col, title=col,color_discrete_sequence=['blue']).show()
    px.box(data_frame=df, x=col, title=col,color_discrete_sequence=['red']).show()

In [14]:
# relationship between features and target columns
corr_df = df.corr(numeric_only=True).round(2)
px.imshow( corr_df,text_auto=True,color_continuous_scale='RdBu')

# Feature Engineering

In [15]:
df

,unixtime,data,time,radiation,temperature,pressure,humidity,winddirection(degrees),speed,timesunrise,timesunset
0,1475229326,9/29/2016 12:00:00 AM,23:55:26,1.21,48,30.46,59,177.39,5.62,06:13:00,18:13:00
1,1475229023,9/29/2016 12:00:00 AM,23:50:23,1.21,48,30.46,58,176.78,3.37,06:13:00,18:13:00
2,1475228726,9/29/2016 12:00:00 AM,23:45:26,1.23,48,30.46,57,158.75,3.37,06:13:00,18:13:00
3,1475228421,9/29/2016 12:00:00 AM,23:40:21,1.21,48,30.46,60,137.71,3.37,06:13:00,18:13:00
4,1475228124,9/29/2016 12:00:00 AM,23:35:24,1.17,48,30.46,62,104.95,5.62,06:13:00,18:13:00
...,...,...,...,...,...,...,...,...,...,...,...
32681,1480587604,12/1/2016 12:00:00 AM,00:20:04,1.22,44,30.43,102,145.42,6.75,06:41:00,17:42:00
32682,1480587301,12/1/2016 12:00:00 AM,00:15:01,1.17,44,30.42,102,117.78,6.75,06:41:00,17:42:00
32683,1480587001,12/1/2016 12:00:00 AM,00:10:01,1.20,44,30.42,102,145.19,9.00,06:41:00,17:42:00
32684,1480586702,12/1/2016 12:00:00 AM,00:05:02,1.23,44,30.42,101,164.19,7.87,06:41:00,17:42:00
32685,1480586402,12/1/2016 12:00:00 AM,00:00:02,1.20,44,30.43,101,83.59,3.37,06:41:00,17:42:00

In [16]:
 #  Combine date + time
df["datetime"] = pd.to_datetime(df["data"].str.split().str[0] + " " + df["time"],format="%m/%d/%Y %H:%M:%S",errors="coerce")

In [17]:
df["month"] = df["datetime"].dt.month

In [18]:
# 3) Time features
df["hour"] = df["datetime"].dt.hour
df["minute"] = df["datetime"].dt.minute
df["second"] = df["datetime"].dt.second

In [19]:
 # 4) Sunrise / Sunset parsing
df["sunrise_dt"] = pd.to_datetime(df["timesunrise"], format="%H:%M:%S", errors="coerce")
df["sunset_dt"] = pd.to_datetime(df["timesunset"], format="%H:%M:%S", errors="coerce")

In [20]:
df["sunrise_minutes"] = ( df["sunrise_dt"].dt.hour * 60 + df["sunrise_dt"].dt.minute + df["sunrise_dt"].dt.second / 60)
##

df["sunset_minutes"] = ( df["sunset_dt"].dt.hour * 60 + df["sunset_dt"].dt.minute + df["sunset_dt"].dt.second / 60)

In [21]:
# current time in minutes from midnight
df["current_minutes"] = df["hour"] * 60 + df["minute"] + df["second"] / 60

In [22]:
 # relative to sunrise/sunset

df["minutes_since_sunrise"] = df["current_minutes"] - df["sunrise_minutes"]
df["minutes_to_sunset"] = df["sunset_minutes"] - df["current_minutes"]

In [23]:
# To show the whole columns
pd.set_option('display.max_columns', None)

In [24]:
df

,unixtime,data,time,radiation,temperature,pressure,humidity,winddirection(degrees),speed,timesunrise,timesunset,datetime,month,hour,minute,second,sunrise_dt,sunset_dt,sunrise_minutes,sunset_minutes,current_minutes,minutes_since_sunrise,minutes_to_sunset
0,1475229326,9/29/2016 12:00:00 AM,23:55:26,1.21,48,30.46,59,177.39,5.62,06:13:00,18:13:00,2016-09-29 23:55:26,9,23,55,26,1900-01-01 06:13:00,1900-01-01 18:13:00,373.0,1093.0,1435.433333,1062.433333,-342.433333
1,1475229023,9/29/2016 12:00:00 AM,23:50:23,1.21,48,30.46,58,176.78,3.37,06:13:00,18:13:00,2016-09-29 23:50:23,9,23,50,23,1900-01-01 06:13:00,1900-01-01 18:13:00,373.0,1093.0,1430.383333,1057.383333,-337.383333
2,1475228726,9/29/2016 12:00:00 AM,23:45:26,1.23,48,30.46,57,158.75,3.37,06:13:00,18:13:00,2016-09-29 23:45:26,9,23,45,26,1900-01-01 06:13:00,1900-01-01 18:13:00,373.0,1093.0,1425.433333,1052.433333,-332.433333
3,1475228421,9/29/2016 12:00:00 AM,23:40:21,1.21,48,30.46,60,137.71,3.37,06:13:00,18:13:00,2016-09-29 23:40:21,9,23,40,21,1900-01-01 06:13:00,1900-01-01 18:13:00,373.0,1093.0,1420.350000,1047.350000,-327.350000
4,1475228124,9/29/2016 12:00:00 AM,23:35:24,1.17,48,30.46,62,104.95,5.62,06:13:00,18:13:00,2016-09-29 23:35:24,9,23,35,24,1900-01-01 06:13:00,1900-01-01 18:13:00,373.0,1093.0,1415.400000,1042.400000,-322.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32681,1480587604,12/1/2016 12:00:00 AM,00:20:04,1.22,44,30.43,102,145.42,6.75,06:41:00,17:42:00,2016-12-01 00:20:04,12,0,20,4,1900-01-01 06:41:00,1900-01-01 17:42:00,401.0,1062.0,20.066667,-380.933333,1041.933333
32682,1480587301,12/1/2016 12:00:00 AM,00:15:01,1.17,44,30.42,102,117.78,6.75,06:41:00,17:42:00,2016-12-01 00:15:01,12,0,15,1,1900-01-01 06:41:00,1900-01-01 17:42:00,401.0,1062.0,15.016667,-385.983333,1046.983333
32683,1480587001,12/1/2016 12:00:00 AM,00:10:01,1.20,44,30.42,102,145.19,9.00,06:41:00,17:42:00,2016-12-01 00:10:01,12,0,10,1,1900-01-01 06:41:00,1900-01-01 17:42:00,401.0,1062.0,10.016667,-390.983333,1051.983333
32684,1480586702,12/1/2016 12:00:00 AM,00:05:02,1.23,44,30.42,101,164.19,7.87,06:41:00,17:42:00,2016-12-01 00:05:02,12,0,5,2,1900-01-01 06:41:00,1900-01-01 17:42:00,401.0,1062.0,5.033333,-395.966667,1056.966667
32685,1480586402,12/1/2016 12:00:00 AM,00:00:02,1.20,44,30.43,101,83.59,3.37,06:41:00,17:42:00,2016-12-01 00:00:02,12,0,0,2,1900-01-01 06:41:00,1900-01-01 17:42:00,401.0,1062.0,0.033333,-400.966667,1061.966667

In [25]:
# drop unnecessary columns
df.drop(columns=["unixtime", "data", "time", "datetime", "sunrise_dt", "sunset_dt", "current_minutes",'timesunrise','timesunset'],axis=1,inplace=True)

In [26]:
df

,radiation,temperature,pressure,humidity,winddirection(degrees),speed,month,hour,minute,second,sunrise_minutes,sunset_minutes,minutes_since_sunrise,minutes_to_sunset
0,1.21,48,30.46,59,177.39,5.62,9,23,55,26,373.0,1093.0,1062.433333,-342.433333
1,1.21,48,30.46,58,176.78,3.37,9,23,50,23,373.0,1093.0,1057.383333,-337.383333
2,1.23,48,30.46,57,158.75,3.37,9,23,45,26,373.0,1093.0,1052.433333,-332.433333
3,1.21,48,30.46,60,137.71,3.37,9,23,40,21,373.0,1093.0,1047.350000,-327.350000
4,1.17,48,30.46,62,104.95,5.62,9,23,35,24,373.0,1093.0,1042.400000,-322.400000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32681,1.22,44,30.43,102,145.42,6.75,12,0,20,4,401.0,1062.0,-380.933333,1041.933333
32682,1.17,44,30.42,102,117.78,6.75,12,0,15,1,401.0,1062.0,-385.983333,1046.983333
32683,1.20,44,30.42,102,145.19,9.00,12,0,10,1,401.0,1062.0,-390.983333,1051.983333
32684,1.23,44,30.42,101,164.19,7.87,12,0,5,2,401.0,1062.0,-395.966667,1056.966667
32685,1.20,44,30.43,101,83.59,3.37,12,0,0,2,401.0,1062.0,-400.966667,1061.966667

In [27]:
df.isna().sum()

radiation                 0
temperature               0
pressure                  0
humidity                  0
winddirection(degrees)    0
speed                     0
month                     0
hour                      0
minute                    0
second                    0
sunrise_minutes           0
sunset_minutes            0
minutes_since_sunrise     0
minutes_to_sunset         0
dtype: int64

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
# after checking the model, there are columns that are not important for the model  i will drop them 
df.drop(columns=['speed', 'minute', 'month', 'sunrise_minutes', 'second','sunset_minutes'], inplace=True,axis=1,)
df.duplicated().sum()

np.int64(0)

In [30]:
df

,radiation,temperature,pressure,humidity,winddirection(degrees),hour,minutes_since_sunrise,minutes_to_sunset
0,1.21,48,30.46,59,177.39,23,1062.433333,-342.433333
1,1.21,48,30.46,58,176.78,23,1057.383333,-337.383333
2,1.23,48,30.46,57,158.75,23,1052.433333,-332.433333
3,1.21,48,30.46,60,137.71,23,1047.350000,-327.350000
4,1.17,48,30.46,62,104.95,23,1042.400000,-322.400000
...,...,...,...,...,...,...,...,...
32681,1.22,44,30.43,102,145.42,0,-380.933333,1041.933333
32682,1.17,44,30.42,102,117.78,0,-385.983333,1046.983333
32683,1.20,44,30.42,102,145.19,0,-390.983333,1051.983333
32684,1.23,44,30.42,101,164.19,0,-395.966667,1056.966667
32685,1.20,44,30.43,101,83.59,0,-400.966667,1061.966667

In [31]:
df.to_csv('Cleaned_Data.csv',index=False)

# Data Analysis

In [32]:
# check the relationship between numerical features and target column
num_cols = df.select_dtypes(include='number').columns
for col in num_cols:
    print(col)
    print('the relactionship : ',df[col].corr(df['radiation']))
    print('_'*50 )

radiation
the relactionship :  0.9999999999999998
__________________________________________________
temperature
the relactionship :  0.7349547554357317
__________________________________________________
pressure
the relactionship :  0.11901565785081028
__________________________________________________
humidity
the relactionship :  -0.2261706471279863
__________________________________________________
winddirection(degrees)
the relactionship :  -0.23032354942178712
__________________________________________________
hour
the relactionship :  0.004397776834593535
__________________________________________________
minutes_since_sunrise
the relactionship :  0.007812644813369808
__________________________________________________
minutes_to_sunset
the relactionship :  -0.0025211209700471103
__________________________________________________

In [33]:
# the distrubtion for target 
import plotly.express as px

fig = px.histogram(
    data_frame=df,
    x='radiation',
    nbins=20,
    color_discrete_sequence=['yellow']
)

fig.show()

In [34]:
# the relationship between hour and radiation
hourly_rad = df.groupby('hour')['radiation'].mean().reset_index()
hourly_rad

px.line(data_frame=hourly_rad,x='hour',y='radiation',)

# Pre-For Machine Learning

In [35]:
df

,radiation,temperature,pressure,humidity,winddirection(degrees),hour,minutes_since_sunrise,minutes_to_sunset
0,1.21,48,30.46,59,177.39,23,1062.433333,-342.433333
1,1.21,48,30.46,58,176.78,23,1057.383333,-337.383333
2,1.23,48,30.46,57,158.75,23,1052.433333,-332.433333
3,1.21,48,30.46,60,137.71,23,1047.350000,-327.350000
4,1.17,48,30.46,62,104.95,23,1042.400000,-322.400000
...,...,...,...,...,...,...,...,...
32681,1.22,44,30.43,102,145.42,0,-380.933333,1041.933333
32682,1.17,44,30.42,102,117.78,0,-385.983333,1046.983333
32683,1.20,44,30.42,102,145.19,0,-390.983333,1051.983333
32684,1.23,44,30.42,101,164.19,0,-395.966667,1056.966667
32685,1.20,44,30.43,101,83.59,0,-400.966667,1061.966667

In [36]:
# slit the data into features and target
x = df.drop('radiation',axis=1)
y = df['radiation']

In [37]:
num_cols = x.select_dtypes(include='number').columns

In [38]:
# numerical pipeline
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler
num_pipeline = Pipeline([
    ('Scaler', RobustScaler()) ])
num_pipeline

Pipeline(steps=[('Scaler', RobustScaler())])

In [ ]:
# apply the numerical pipeline to the numerical columns
from sklearn.compose import ColumnTransformer
preprocessing = ColumnTransformer([('Numerical Pipeline', num_pipeline, num_cols) ], remainder='passthrough')
preprocessing

ColumnTransformer(remainder='passthrough',
                  transformers=[('Numerical Pipeline',
                                 Pipeline(steps=[('Scaler', RobustScaler())]),
                                 Index(['temperature', 'pressure', 'humidity', 'winddirection(degrees)', 'hour',
       'minutes_since_sunrise', 'minutes_to_sunset'],
      dtype='object'))])

In [40]:
import warnings
warnings.filterwarnings("ignore")

In [42]:
from sklearn.model_selection import cross_validate
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
#from sklearn.svm import SVR
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
#-----------------------------------------------------------------------
models = [
    ('Linear Regression', LinearRegression()),
    ('KNN Regressor', KNeighborsRegressor()),
    ('Decision Tree Regressor', DecisionTreeRegressor(random_state=42)),
    ('Random Forest Regressor', RandomForestRegressor(random_state=42)),
   # ('Support Vector Regressor', SVR()),
    ('CatBoost Regressor', CatBoostRegressor( random_state=42, verbose=0)),
    ('XGBoost Regressor', XGBRegressor(random_state=42, verbosity=0)),
    ('LightGBM Regressor', LGBMRegressor(random_state=42, verbose=-1))
]
#-----------------------------------------------------------------------
for model in models:
        model_pipline = Pipeline(steps=[('Preprocessing',preprocessing),('Model',model[1])])
        result = cross_validate(model_pipline, x, y, cv=5 , scoring=['r2'], return_train_score=True)
        print(model[0])
        print('Train R2:', np.mean(result['train_r2']))
        print('Test R2:', np.mean(result['test_r2']).round(4))
        print('_'*50)

Linear Regression
Train R2: 0.6175532463635172
Test R2: 0.5724
__________________________________________________
KNN Regressor
Train R2: 0.9377802958788306
Test R2: 0.7476
__________________________________________________
Decision Tree Regressor
Train R2: 1.0
Test R2: 0.6643
__________________________________________________
Random Forest Regressor
Train R2: 0.9896458723155467
Test R2: 0.802
__________________________________________________
CatBoost Regressor
Train R2: 0.9473769706296047
Test R2: 0.797
__________________________________________________
XGBoost Regressor
Train R2: 0.9665495318018691
Test R2: 0.785
__________________________________________________
LightGBM Regressor
Train R2: 0.9366601743357691
Test R2: 0.8076
__________________________________________________

In [43]:
from sklearn.model_selection import RandomizedSearchCV
from lightgbm import LGBMRegressor
para_grid = {
    'Model__n_estimators': [100, 200, 300,500, 800],
    'Model__learning_rate': [0.01, 0.03,0.05, 0.1],
    'Model__max_depth': [3,4, 5,6, 7],
    'Model__num_leaves': [20, 30, 40]
}
model_pipline = Pipeline(steps=[('Preprocessing',preprocessing),('Model',LGBMRegressor(random_state=42))])
random_search = RandomizedSearchCV(estimator=model_pipline, param_distributions=para_grid, n_iter=10, cv=5, scoring='r2', n_jobs=-1, random_state=42)

random_search.fit(x, y)

print("Best Score:", random_search.best_score_)
print("Best Params:", random_search.best_params_)

Best Score: 0.8188117907379017
Best Params: {'Model__num_leaves': 30, 'Model__n_estimators': 200, 'Model__max_depth': 5, 'Model__learning_rate': 0.03}

In [ ]:
best_model = random_search.best_estimator_
lgbm_model = best_model.named_steps['Model']
import pandas as pd

feature_importance = pd.DataFrame({
    'Feature': best_model.named_steps['Preprocessing'].get_feature_names_out(),
    'Importance': lgbm_model.feature_importances_
})

feature_importance = feature_importance.sort_values(
    by='Importance',
    ascending=False
)

print(feature_importance)

                                      Feature  Importance
5   Numerical Pipeline__minutes_since_sunrise        1175
6       Numerical Pipeline__minutes_to_sunset        1166
2                Numerical Pipeline__humidity         921
1                Numerical Pipeline__pressure         767
0             Numerical Pipeline__temperature         753
3  Numerical Pipeline__winddirection(degrees)         668
4                    Numerical Pipeline__hour         160

In [ ]:
px.bar(feature_importance, x='Feature', y='Importance', color_discrete_sequence=['blue'], text_auto=True)

In [ ]:
random_search.cv_results_['mean_test_score'].mean().round(2) * 100

np.float64(80.0)

In [ ]:
random_search.best_score_ * 100

np.float64(81.88117907379016)

In [ ]:
final_pipeline = Pipeline(steps=[('Preprocessing',preprocessing),('Model',LGBMRegressor(random_state=42, n_estimators=200, max_depth=5, num_leaves=30, learning_rate=0.03))])
final_pipeline.fit(x, y)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Numerical Pipeline',
                                                  Pipeline(steps=[('Scaler',
                                                                   RobustScaler())]),
                                                  Index(['temperature', 'pressure', 'humidity', 'winddirection(degrees)', 'hour',
       'minutes_since_sunrise', 'minutes_to_sunset'],
      dtype='object'))])),
                ('Model',
                 LGBMRegressor(learning_rate=0.03, max_depth=5,
                               n_estimators=200, num_leaves=30,
                               random_state=42))])

In [ ]:
import joblib
joblib.dump(final_pipeline, 'SolarPrediction_model.pkl')

['SolarPrediction_model.pkl']

## Streamlit Page

In [ ]:
! streamlit run Overview.py

^C

In [44]:
import pipreqs 
! pipreqs .

INFO: Not scanning for jupyter notebooks.
WARNING: Import named "numpy" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "numpy" was resolved to "numpy:2.4.6" package (https://pypi.org/project/numpy/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
WARNING: Import named "pandas" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "pandas" was resolved to "pandas:3.0.3" package (https://pypi.org/project/pandas/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
INFO: Successfully saved requirements file in .\requirements.txt